# Generated by Django 4.2.2 on 2023-06-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Przychod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.kategoria')),
            ],
        ),
    ]
